### PR TITLE
Fix memo render reason

### LINKED ISSUE #343: [Bug][v4.0.2] False negative for "Force update" render reason on Profiler
Hey folks 👋. Yesterday 7th May I started to get a false negative render reason for `Force update` in a memorized component when its pros didn't change.

**Browser**: Chrome `101.0.4951.54`
**Preact Dev Tools Version:**: `v4.0.2`

**Previous Behaviour**: In the version `v1.4.4` the render reason for `Memo(Button)` is `Parent updated` (This is expected because the state for the parent component  `Part1` changed). Also, the child component `Memo` didn't appear in the "Ranked" chart, it didn't render at all. 

**Current Behavior**: In the version `v4.0.2` the render reason for `Memo(Button)` is `Force update`, and it tells the `Button` component was rendered too but I was able to confirm is not being rendered at all.

Here is the component I was using to test: https://github.com/marconi1992/preact-redux-performance/blob/b9c0d962ddac02bb3d10e15a152543ee279d1a7b/src/routes/part-1/solution.jsx

Version `v4.0.2`

image

Version `v1.4.4`

image

`

### PR DESCRIPTION
**Pull request by marvinhagemeister**
I think I have a good idea on how to fix this, but it will take a bit of time as it touches a few areas.

- [x] Add test case
- [x] Fix the issue

Fixes #343

### CODE REVIEW

**Comment by marconi1992** [comment]
FWIW the issue is solved in my side 😄 
image

Really cool E2E tests!

**Review by marconi1992 — APPROVED** [review]
LGTM!

File: test-e2e/fixtures/apps/render-reasons-memo.jsx [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+}
+
+function App() {
+	const [v, set] = useState(0);
+
+	return (
+		<AppInner>
+			<div>
+				<button onClick={() => set(v + 1)}>Update</button>
+				<MemoFoo />
```
Comment (marconi1992) [inline test-e2e/fixtures/apps/render-reasons-memo.jsx:26]: Sorry, I found an issue when we include another memorized component that iterates over an array to return a more complex output (list of elements). 

https://github.com/preactjs/preact-devtools/pull/359

**Review by marconi1992 — CHANGES_REQUESTED** [review]
